### PR TITLE
#483: fixed node tool installations

### PR DESCRIPTION
**Pull request by hohwille**
Fixes bug issue #483 and ensures that `node`, `npm` and `ng` are always taken from `devonfw-ide` sandbox installtion avoiding side effects from global installations.

### CODE REVIEW

**Comment by hohwille** [comment]
Quite sensible change but IMHO all as it should always have been.
However, we would need some advanced testing from `node.js` users for the next release.

**Comment by hohwille** [comment]
Travis failed with this error:
```
npm ERR! code EEXIST
npm ERR! syscall symlink
npm ERR! path ../lib/node_modules/angular-cli/bin/ng
npm ERR! dest /home/travis/build/devonfw/ide/scripts/target/integration-test/test-setup/software/node/bin/ng
npm ERR! errno -17
npm ERR! EEXIST: file already exists, symlink '../lib/node_modules/angular-cli/bin/ng' -> '/home/travis/build/devonfw/ide/scripts/target/integration-test/test-setup/software/node/bin/ng'
npm ERR! File exists: /home/travis/build/devonfw/ide/scripts/target/integration-test/test-setup/software/node/bin/ng
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.
```

Looks like global side-effects of npm installation still affects here. Can someone assist who actually likes and uses these tools?

**Review by sjimenez77 — APPROVED** [review]
Hi @hohwille, the PR looks good to me and could be merged. Anyhow I am not a bash expert...

**Comment by sjimenez77** [comment]
Maybe this is a bit off topic, but have you checked if command `npx` that comes with any recent `npm` installation is accesible from a devonfw ide installation? (I will check it next Monday in any case).

FYI https://github.com/npm/npx#readme

**Comment by sjimenez77** [comment]
Just checked `npx` and it works like a charm. In the context of a devonfw IDE instance the one inside is used and outside that context the one from global `npm` installation is called.

**Comment by hohwille** [comment]
@sjimenez77 thanks for review and feedback.
Regarding `npx` I am not quite sure if I fully understood. But sounds like we could add a valuable hint about `npx` in the `npm` documentation of `devonfw-ide`.

**Pull request merged**
