### PR TITLE
#786 Improve Windows Terminal with powershell

### PR DESCRIPTION
**Pull request by CREITZ25**
#786 Improve Windows Terminal with powershell

### CODE REVIEW

**Review by tobka777 — APPROVED** [review]
@CREITZ25 looks very good. Have you done a test on Windows starting with a new devon installation?

**Comment by tobka777** [comment]
Please solve the merge conflict with `setup.bat`.

**Comment by CREITZ25** [comment]
@tobka777 Now it is testet in a new environment, and I had to correct something, because an already fixed bug was in my installation. I don't know why...

**Review by tobka777 — APPROVED** [review]

**Review by hohwille — APPROVED** [review]
@CREITZ25 Thanks for this PR and great that you could even solve this for PowerShell and complete the story about Windows Terminal. 👍 
You also changed the registry files for CMD and gitbash alongside with this PR. I can not see the diffs here on github as it treats them as binary. What was the reason for that change?

**Comment by CREITZ25** [comment]
You are not able to see changes because these are reg files. The change in the reg files are:
From:
"%USERPROFILE%\AppData\Local\Microsoft\WindowsApps\wt.exe"  -w 0 new-tab -p "Windows Powershell" --title "**devon PowerShell**" -d %L PowerShell.exe -NoExit -Command "devon" 
To:
"%USERPROFILE%\AppData\Local\Microsoft\WindowsApps\wt.exe"  -w 0 new-tab -p "Windows Powershell" --title "**devonfw PowerShell**" -d %L PowerShell.exe -NoExit -Command "devon"

**Comment by hohwille** [comment]
> I corrected it, but I add it to the other (the last) issue/PR

I was more asking about the reg files for CMD and gitbash but I will assume that you also changed those accordingly.
So is this `hex(2)` blabla magic just an hex conversion of the actual command that you somehow encode with a specific tool?
Could you be so kind and document this magic process e.g. in #701 or even better in a `README` [here](https://github.com/devonfw/ide/tree/master/scripts/src/main/resources/system/windows/windows-terminal)?

**Pull request merged**
