### PR TITLE
#786 add readme to windows terminal with Powershell, cmd and GitBash

### PR DESCRIPTION
**Pull request by CREITZ25**
I created the readme file for this three extensions

### CODE REVIEW

**Comment by hohwille** [comment]
I was initially referring to such magic hex code:
https://github.com/devonfw/ide/blob/d5a35311f7ae80f682fd76746e92537b7404fde4/scripts/src/main/resources/system/windows/windows-terminal/devon-wt-cmd.reg#L7

I might miss something but the README your created does not relate to that hex stuff and how to create it.

**Comment by hohwille** [comment]
Maybe you wanted to explain in the readme that you are doing this temporary stuff manually in `regedit` and then at the end export the hex stuff from there to create the reg file. If that is the case, then you are one the right way but the readme needs some more details so that others can understand what you want to say. The explanation of the rationale with variables otherwise not working is already very helpful to get a motivation why all this is required here...

**Comment by CREITZ25** [comment]
Extension of the readme.asciidoc with a step-by-step guide

**Review by hohwille — APPROVED** [review]
@CREITZ25 thanks for the update. Now everything gets clear. Awesome 👍

**Pull request merged**
