### PR TITLE
Feature/wt

### PR DESCRIPTION
**Pull request by CREITZ25**
Little bugfix for devon CMD in Windows Terminal.  Title is now set to "devon CMD"

### CODE REVIEW

**Review by tobka777 — APPROVED** [review]
Thanks. We should take care that the path is "wt-cmd" everywhere at the end.

**Comment by hohwille** [comment]
>  Title is now set to "devon CMD"

When it is about documentation, titles, etc. can you please always use the registered trademark `devonfw` instead of `devon`?

**Comment by CREITZ25** [comment]
I corrected it, but I add it to the other (the last) issue/PR:

#786 Improve Windows Terminal with powershell

**Comment by hohwille** [comment]
> I corrected it, but I add it to the other (the last) issue/PR: #786

Great, thanks. So I close this issue and we focus on getting #786 merged.
If I got something wrong, feel free to reopen and comment :)

**Pull request closed without merging**
