### PR TITLE
#514: adjusted AnyEditTools update site URL

### LINKED ISSUE #514: Remove or adjust AnyEditTools plugin update site
The current URL: http://andrei.gmxhome.de/eclipse/ is dead and needs to be removed/replaced.

###Comments:

The old Eclipse update site for all my plugins is moved now: from http://andrei.gmxhome.de/eclipse/ to https://raw.githubusercontent.com/iloveeclipse/plugins/latest/. Same way, my "home" is moved to https://github.com/iloveeclipse/plugins/wiki.

### Affected version:

devonfw-ide: 2020.12.001

### PR DESCRIPTION
**Pull request by jan-vcapgemini**
fixes #514 by correcting AnyEditTools update site URL.

### CODE REVIEW

**Review by hohwille — APPROVED** [review]
@jan-vcapgemini thanks for this awesome PR. 👍 
You even fixed the links in the LICENSE details. Unfortunately I picked this plugin as example in the documentation so this also had to be changed. However, you missed the most imporant part:
https://github.com/devonfw/ide-settings/blob/3e7f3c960e651109cf467664933f0074e482a6a4/eclipse/plugins/anyedit.properties#L1

I will immediately fix this as well and we can include submodule update.
Could you include this into this PR (go to `settings/src/main/settings` and update to latest master, then commit the submodule update on the top git repo itself)?
Otherwise, let me know and I will merge this PR and do that afterwards myself.

**Comment by hohwille** [comment]
https://github.com/devonfw/ide-settings/commit/2c7d31ffe46770c3344ff8ae019e3275852c0ec5

**Comment by hohwille** [comment]
I really love if we receive valuable contributions like this. We should give awards for such PRs :)

**Comment by jan-vcapgemini** [comment]
> 
> 
> @jan-vcapgemini thanks for this awesome PR. 👍
> You even fixed the links in the LICENSE details. Unfortunately I picked this plugin as example in the documentation so this also had to be changed. However, you missed the most imporant part:
> https://github.com/devonfw/ide-settings/blob/3e7f3c960e651109cf467664933f0074e482a6a4/eclipse/plugins/anyedit.properties#L1
> 
> I will immediately fix this as well and we can include submodule update.
> Could you include this into this PR (go to `settings/src/main/settings` and update to latest master, then commit the submodule update on the top git repo itself)?
> Otherwise, let me know and I will merge this PR and do that afterwards myself.

I've updated the settings submodule and commited the update to this PR. I was wondering why my local tests were failing with the old URL the whole time, now I know why :)

**Pull request merged**
