### PR TITLE
Update yarn

### PR DESCRIPTION
**Pull request by OliverNeff**
`install` has been replaced with `add` to add new dependencies.

### CODE REVIEW

**Comment by hohwille** [comment]
Can you give a link or more details? Don't we need downward compatibility?
So would we need to check `YARN_VERSION` and only if newer than `«x.y.z»` apply this change?

**Comment by hohwille** [comment]
@OliverNeff I assume this is a misunderstanding.
* `yarn add` is for adding a dependency: https://classic.yarnpkg.com/en/docs/cli/add/
* `yarn install` is for building: https://classic.yarnpkg.com/en/docs/cli/install/

I think this PR is invalid and can be closed.
Agreement or do you have insights what I might be missing?

**Comment by OliverNeff** [comment]
@hohwille,
I installed the IDE with YARN and not NPM and become this installation in the installation process. When I changed it to add it worked for me.

**Comment by hohwille** [comment]
Feedback from @dario-rodriguez on teams:
> What is the purpose of the doRunBuild function? Build the application? In that case you need to call to yarn build (build script must be present in package.json). If node_modules folder is not present you must call yarn install (or only yarn) before you execute the yarn build command. So, in my opinion, both implementations (the PR and the previous code) are wrong.

I fully agree and therefore my suggestion is to close this PR as invalid and create a new issue/PR to fix this properly.

**Comment by hohwille** [comment]
Created issue #431 and closing this PR. We have to create a new PR to fix #431.

**Comment by hohwille** [comment]
For the record. I fully understood the problem only while implementing the fix. So unlike in maven (`mvn`) the JavaScript build tools like `npm` and `yarn` do not allow to simply concatenate goals as the goals may take parameters.
Therefore `devon install build` is not first running `install` and running `build` script, but will add and install the dependency `build` as it is provided as argument to `install`. This is also leading to the message that instead `add` shall be used and this fully explains the change proposed in this PR.
However, the correct fix was:
* prevent to implicitly add `install` goal if `node_modules` is not present
* for build command simply first run `install` and then in a second invocation call `run build` (but only if `build` section is present in `package.json` under `scripts`).

So again thanks for the PR and contribution. It took a while but it finally lead to a fix and helped improving `devonfw-ide` 👍

**Pull request closed without merging**
