### PR TITLE
#456: add condition around variable expansion

### PR DESCRIPTION
**Pull request by markusschuh**
The closing curly brace should only be replaced, when a variable expansion is necessary.

### CODE REVIEW

**Review by hohwille — APPROVED** [review]
@markusschuh Looks good and functionally correct to me. Thanks for this PR 👍 
Did you check performance (that is already a little slow on windows)?
Assuming no `${...}` will be found will this be as fast or even faster as before?

**Comment by hohwille** [comment]
I see this as ready to be merged but give some time for @markusschuh in case he wants to anwer to my questions from review.

**Comment by hohwille** [comment]
Regarding `findstr` I found some comments about performance here:
https://stackoverflow.com/questions/34058575/improve-windowss-batch-script-performance
So it seems not very fast and is executed for every line and always has to parse and apply the regex.

**Comment by mperezor19** [comment]
Hi,  I tested executing 'devon' command in  this feature branch and master branch and the executions time have significant difference:

Feature branch:
measure command 1
measure command 2
measure command 3
measure command 4
measure command 5


Master branch:
measure-master-5
measure-master-1
measure-master-2
measure-master-3
measure-master-4

Also mention that there is a test in this branch which is causing error when build, the regex should be modified like this:
test-fix

**Comment by hohwille** [comment]
Thanks  @mperezor19 for your tests and analysis.
Do I read your results properly such that the result is the execution of running plain `devon` command (parsing properties and setting env variables) takes more than twice as much execution time with this PR applied?
Then my gut feeling was correct and we should not merge without further action/decision making.

Your second point IMHO does not seem to be related to this PR at all. Anyway also thanks for that feedback. So you are talking about this:
https://github.com/devonfw/ide/blob/4328c88f087d671889b2273f34ee01fa537a7cc1/configurator/src/test/java/com/devonfw/tools/ide/configurator/SortedPropertiesTest.java#L27

If I am not mistaken, the problem relates to different EOL encoding and only happens on windows. As I am using MacOS and our travis CI build is using Linux both are not affected. Your fix will only work on windows. So we should add an optional carriage return here so it works on all plattforms. I will file a new issue for this.

**Comment by markusschuh** [comment]
Let's just close this PR. 
I don't share the interpretation that the above time series would show a slow down of "2 times". But sure - forking external commands is insane for performance in any case. Which disqualifies `CMD `- and by the way `bash` as well, even when less - for too complex tasks..

**Pull request closed without merging**
