### PR TITLE
Switching message on success to "Successfully <past>"

### PR DESCRIPTION
**Pull request by ThomasRot**
Just a minor grammar fix as to my knowledge "succeed to <infinitiv>" does not exist..

### CODE REVIEW

**Comment by hohwille** [comment]
@ThomasRot thanks for your PR and contributing to devonfw-ide.
Could you explain the rationale for your change?

> Just a minor grammar fix as to my knowledge "succeed to " does not exist..

It actually is `Succeeded to `:
https://github.com/devonfw/ide/blob/08129217e563666a7546f40f41665377634c665e/scripts/src/main/resources/scripts/functions#L91
Further there are multiple places for this (you only changed one of them):
https://github.com/devonfw/ide/blob/08129217e563666a7546f40f41665377634c665e/scripts/src/main/resources/scripts/functions#L50

According to English grammar the current state is fully correct:
https://www.collinsdictionary.com/dictionary/english/succeed
> George III succeeded to the throne in 1760.

I do not see the need for this change and would close it if I am not missing anything.
Any concerns or corrections?

**Comment by hohwille** [comment]
I have created PR #802 as a simple fix and replacement for this PR.
If OK, I would close this PR and merge #802 to resolve the actual issue.

**Comment by hohwille** [comment]
@ThomasRot beginning of next week I will close this PR and merge #802 unless you have anything else to report. We try to make continuous progress and releases (again after a time where I was M.I.A.).

**Comment by ThomasRot** [comment]
All good points especially as this change did not consider all implications. I like the solution proposed in #802, so I'm closing this one.

**Pull request closed without merging**
